import Head from "next/head";
// import Image from 'next/image';
import Link from "next/link";

import { addUser, login } from "../store/auth/authSlice";
import { wrapper } from "../store/store";

import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Animal Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Link href="/auth/login">Login</Link>
        <main className={styles.main}>Animal social media</main>
      </div>
    </>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    const response = await fetch(
      `https://reqres.in/api/users/${Math.floor(Math.random() * 10 + 1)}`
    );

    const { data } = await response.json();

    store.dispatch(addUser(`${data.first_name} ${data.last_name}`));
    store.dispatch(login());

    return {
      props: {
        data,
      },
    };
  }
);
